import type { SymptomMapping } from '@/lib/generated/prisma';

export const SYMPTOMMAPPING_DATA: Omit<SymptomMapping, 'id'>[] = [
  {
    keyword: '발열',
    synonyms: '열나요, 고열, 오한, 몸이 뜨거움, 해열제',
    deptName: '내과, 소아청소년과, 가정의학과',
    bodyPart: '전신',
  },
  {
    keyword: '기침',
    synonyms: '콜록콜록, 기침이 멈추지 않음, 마른기침',
    deptName: '이비인후과, 내과',
    bodyPart: '목/호흡기',
  },
  {
    keyword: '콧물',
    synonyms: '코막힘, 비염, 누런 콧물, 재채기',
    deptName: '이비인후과',
    bodyPart: '얼굴/코',
  },
  {
    keyword: '인후통',
    synonyms: '목 아픔, 목이 부음, 침 삼킬 때 아픔, 목소리 변함',
    deptName: '이비인후과, 내과',
    bodyPart: '목',
  },
  {
    keyword: '복통',
    synonyms: '배 아픔, 위통, 배탈, 속 쓰림, 위경련, 배가 콕콕 쑤심',
    deptName: '내과, 가정의학과',
    bodyPart: '배',
  },
  {
    keyword: '설사',
    synonyms: '묽은 변, 장염, 배변 장애',
    deptName: '내과, 가정의학과',
    bodyPart: '배',
  },
  {
    keyword: '변비',
    synonyms: '배변 곤란, 똥이 안 나옴',
    deptName: '내과, 가정의학과',
    bodyPart: '배',
  },
  {
    keyword: '소화불량',
    synonyms: '체함, 더부룩함, 가스 참, 트림',
    deptName: '내과, 가정의학과',
    bodyPart: '배',
  },
  {
    keyword: '두통',
    synonyms: '머리 아픔, 편두통, 머리가 띵함, 머리가 무거움',
    deptName: '내과, 신경과',
    bodyPart: '머리',
  },
  {
    keyword: '어지러움',
    synonyms: '빈혈 기운, 어지럼증, 현기증, 핑 도는 느낌',
    deptName: '이비인후과, 신경과, 내과',
    bodyPart: '머리',
  },
  {
    keyword: '허리 통증',
    synonyms: '요통, 디스크, 허리 삠, 등 통증',
    deptName: '정형외과, 신경외과, 재활의학과',
    bodyPart: '허리/등',
  },
  {
    keyword: '발목 삠',
    synonyms: '접질림, 발목 통증, 인대 늘어남, 발목 부음',
    deptName: '정형외과',
    bodyPart: '다리/발',
  },
  {
    keyword: '무릎 통증',
    synonyms: '관절염, 무릎 아픔, 뚜둑 소리 남',
    deptName: '정형외과, 재활의학과',
    bodyPart: '다리/발',
  },
  {
    keyword: '어깨 통증',
    synonyms: '오십견, 어깨 결림, 팔 안 올라감',
    deptName: '정형외과, 재활의학과',
    bodyPart: '팔/어깨',
  },
  {
    keyword: '손목 통증',
    synonyms: '손목 터널 증후군, 손목 시림',
    deptName: '정형외과, 재활의학과',
    bodyPart: '팔/어깨',
  },
  {
    keyword: '가려움',
    synonyms: '피부 간지러움, 두드러기, 습진',
    deptName: '피부과',
    bodyPart: '피부',
  },
  {
    keyword: '발진',
    synonyms: '두드러기, 붉은 반점, 피부 트러블',
    deptName: '피부과',
    bodyPart: '피부',
  },
  {
    keyword: '화상',
    synonyms: '데임, 뜨거운 것에 닿음, 물집',
    deptName: '피부과, 외과',
    bodyPart: '피부',
  },
  {
    keyword: '눈 충혈',
    synonyms: '결막염, 눈 빨개짐, 눈 곱, 눈 아픔',
    deptName: '안과',
    bodyPart: '얼굴/눈',
  },
  {
    keyword: '안구 건조',
    synonyms: '눈 뻑뻑함, 눈 깔깔함, 눈물 부족',
    deptName: '안과',
    bodyPart: '얼굴/눈',
  },
  {
    keyword: '시력 저하',
    synonyms: '눈이 침침함, 안 보임, 흐릿함',
    deptName: '안과',
    bodyPart: '얼굴/눈',
  },
  {
    keyword: '치통',
    synonyms: '이 아픔, 잇몸 통증, 시린 이, 충치',
    deptName: '치과',
    bodyPart: '얼굴/입',
  },
  {
    keyword: '잇몸 부음',
    synonyms: '피 남, 잇몸 통증, 치주염',
    deptName: '치과',
    bodyPart: '얼굴/입',
  },
  {
    keyword: '이명',
    synonyms: '귀에서 소리 남, 삐 소리',
    deptName: '이비인후과',
    bodyPart: '얼굴/귀',
  },
  {
    keyword: '귀 먹먹함',
    synonyms: '물 들어간 느낌, 안 들림, 중이염',
    deptName: '이비인후과',
    bodyPart: '얼굴/귀',
  },
  {
    keyword: '비염',
    synonyms: '코 가려움, 재채기, 알레르기',
    deptName: '이비인후과',
    bodyPart: '얼굴/코',
  },
  {
    keyword: '축농증',
    synonyms: '코 막힘, 얼굴 통증, 누런 코',
    deptName: '이비인후과',
    bodyPart: '얼굴/코',
  },
  {
    keyword: '불면증',
    synonyms: '잠이 안 옴, 자꾸 깸',
    deptName: '정신건강의학과, 신경과',
    bodyPart: '심리/머리',
  },
  {
    keyword: '우울감',
    synonyms: '무기력함, 슬픔, 마음이 아픔',
    deptName: '정신건강의학과',
    bodyPart: '심리',
  },
  {
    keyword: '불안',
    synonyms: '가슴 두근거림, 공황장애, 초조함',
    deptName: '정신건강의학과',
    bodyPart: '심리',
  },
  {
    keyword: '가슴 통증',
    synonyms: '흉통, 심장 통증, 숨 가쁨',
    deptName: '내과, 흉부외과',
    bodyPart: '가슴',
  },
  {
    keyword: '심장 두근거림',
    synonyms: '부정맥, 가슴 떨림, 숨참',
    deptName: '내과',
    bodyPart: '가슴',
  },
  {
    keyword: '배뇨통',
    synonyms: '오줌 눌 때 아픔, 방광염',
    deptName: '비뇨의학과, 산부인과',
    bodyPart: '비뇨기',
  },
  {
    keyword: '빈뇨',
    synonyms: '화장실 자꾸 감, 잔뇨감',
    deptName: '비뇨의학과, 산부인과',
    bodyPart: '비뇨기',
  },
  {
    keyword: '생리통',
    synonyms: '월경통, 하복부 통증',
    deptName: '산부인과',
    bodyPart: '비뇨기/배',
  },
  {
    keyword: '근육통',
    synonyms: '담 걸림, 온몸이 쑤심, 알 배김',
    deptName: '정형외과, 재활의학과',
    bodyPart: '전신',
  },
  {
    keyword: '마비',
    synonyms: '손발 저림, 감각 없음, 힘이 안 들어감',
    deptName: '신경과, 정형외과',
    bodyPart: '전신/머리',
  },
  {
    keyword: '여드름',
    synonyms: '뾰루지, 피지, 트러블',
    deptName: '피부과',
    bodyPart: '피부',
  },
  {
    keyword: '탈모',
    synonyms: '머리카락 빠짐, 대머리',
    deptName: '피부과',
    bodyPart: '머리',
  },
  {
    keyword: '무좀',
    synonyms: '발 가려움, 발톱 변색',
    deptName: '피부과',
    bodyPart: '다리/발',
  },
  {
    keyword: '피로',
    synonyms: '만성 피로, 기운 없음',
    deptName: '내과, 가정의학과',
    bodyPart: '전신',
  },
  {
    keyword: '손가락 통증',
    synonyms: '방아쇠 수지, 손가락 부음',
    deptName: '정형외과',
    bodyPart: '팔/어깨',
  },
  {
    keyword: '입병',
    synonyms: '구내염, 혓바늘, 입안 헐음',
    deptName: '이비인후과, 치과',
    bodyPart: '얼굴/입',
  },
  {
    keyword: '다리 부음',
    synonyms: '부종, 코끼리 다리, 하체 비만',
    deptName: '내과, 외과',
    bodyPart: '다리/발',
  },
  {
    keyword: '가래',
    synonyms: '목에 이물감, 가래 끓음',
    deptName: '이비인후과, 내과',
    bodyPart: '목',
  },
  {
    keyword: '코피',
    synonyms: '코에서 피 남, 잦은 코피',
    deptName: '이비인후과',
    bodyPart: '얼굴/코',
  },
  {
    keyword: '안면마비',
    synonyms: '입 돌아감, 얼굴 감각 이상',
    deptName: '신경과, 한의원',
    bodyPart: '얼굴',
  },
  {
    keyword: '담석',
    synonyms: '옆구리 통증, 결석',
    deptName: '내과, 비뇨의학과',
    bodyPart: '배',
  },
  {
    keyword: '두드러기',
    synonyms: '팽진, 피부 올라옴',
    deptName: '피부과',
    bodyPart: '피부',
  },
  {
    keyword: '성병',
    synonyms: '은밀한 부위 통증, 성기 문제',
    deptName: '비뇨의학과, 산부인과',
    bodyPart: '비뇨기',
  },
];
