import type { Metadata } from 'next';
<<<<<<< HEAD
import './globals.css';

export const metadata: Metadata = {
  title: 'Hanaro Pass',
  description:
    '한국 생활, 하나로 끝! 모든 방한 외국인을 위한 한국 여정 금융 동반 서비스, 하나로패스',
=======
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
>>>>>>> a68fff0 (HN-40/feat: 신분증 등록 bottom sheet 공통 컴포넌트 구현)
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" suppressHydrationWarning>
      <body className="antialiased">
        <div className="app-shell">{children}</div>
      </body>
    </html>
  );
}
